package gui.properties;

public class SelectableIsntrument {
    public static final SelectableIsntrument[] INSTRUMENTS = new SelectableIsntrument[] {
            new SelectableIsntrument(0, "Acoustic Grand Piano"),
            new SelectableIsntrument(1, "Bright Acoustic Piano"),
            new SelectableIsntrument(2, "Electric Grand Piano"),
            new SelectableIsntrument(3, "Honky-tonk Piano"),
            new SelectableIsntrument(4, "Rhodes Piano"),
            new SelectableIsntrument(5, "Chorused Piano"),
            new SelectableIsntrument(6, "Harpsichord"),
            new SelectableIsntrument(7, "Clavinet"),
            new SelectableIsntrument(8, "Celesta"),
            new SelectableIsntrument(9, "Glockenspiel"),
            new SelectableIsntrument(10, "Music Box"),
            new SelectableIsntrument(11, "Vibraphone"),
            new SelectableIsntrument(12, "Marimba"),
            new SelectableIsntrument(13, "Xylophone"),
            new SelectableIsntrument(14, "Tubular Bells"),
            new SelectableIsntrument(15, "Dulcimer"),
            new SelectableIsntrument(16, "Hammond Organ"),
            new SelectableIsntrument(17, "Percussive Organ"),
            new SelectableIsntrument(18, "Rock Organ"),
            new SelectableIsntrument(19, "Church Organ"),
            new SelectableIsntrument(20, "Reed Organ"),
            new SelectableIsntrument(21, "Accordion"),
            new SelectableIsntrument(22, "Harmonica"),
            new SelectableIsntrument(23, "Tango Accordion"),
            new SelectableIsntrument(24, "Acoustic Nylon Guitar"),
            new SelectableIsntrument(25, "Acoustic Steel Guitar"),
            new SelectableIsntrument(26, "Electric Jazz Guitar"),
            new SelectableIsntrument(27, "Electric Clean Guitar"),
            new SelectableIsntrument(28, "Electric Muted Guitar"),
            new SelectableIsntrument(29, "Overdriven Guitar"),
            new SelectableIsntrument(30, "Distortion Guitar"),
            new SelectableIsntrument(31, "Guitar Harmonics"),
            new SelectableIsntrument(32, "Acoustic Bass"),
            new SelectableIsntrument(33, "Fingered Electric Bass"),
            new SelectableIsntrument(34, "Plucked Electric Bass"),
            new SelectableIsntrument(35, "Fretless Bass"),
            new SelectableIsntrument(36, "Slap Bass 1"),
            new SelectableIsntrument(37, "Slap Bass 2"),
            new SelectableIsntrument(38, "Synth Bass 1"),
            new SelectableIsntrument(39, "Synth Bass 2"),
            new SelectableIsntrument(40, "Violin"),
            new SelectableIsntrument(41, "Viola"),
            new SelectableIsntrument(42, "Cello"),
            new SelectableIsntrument(43, "Contrabass"),
            new SelectableIsntrument(44, "Tremolo Strings"),
            new SelectableIsntrument(45, "Pizzicato Strings"),
            new SelectableIsntrument(46, "Orchestral Harp"),
            new SelectableIsntrument(47, "Timpani"),
            new SelectableIsntrument(48, "String Ensemble 1"),
            new SelectableIsntrument(49, "String Ensemble 2"),
            new SelectableIsntrument(50, "Synth Strings 1"),
            new SelectableIsntrument(51, "Synth Strings 2"),
            new SelectableIsntrument(52, "Choir \"Aah\""),
            new SelectableIsntrument(53, "Choir \"Ooh\""),
            new SelectableIsntrument(54, "Synth Voice"),
            new SelectableIsntrument(55, "Orchestral Hit"),
            new SelectableIsntrument(56, "Trumpet"),
            new SelectableIsntrument(57, "Trombone"),
            new SelectableIsntrument(58, "Tuba"),
            new SelectableIsntrument(59, "Muted Trumpet"),
            new SelectableIsntrument(60, "French Horn"),
            new SelectableIsntrument(61, "Brass Section"),
            new SelectableIsntrument(62, "Synth Brass 1"),
            new SelectableIsntrument(63, "Synth Brass 2"),
            new SelectableIsntrument(64, "Soprano Sax"),
            new SelectableIsntrument(65, "Alto Sax"),
            new SelectableIsntrument(66, "Tenor Sax"),
            new SelectableIsntrument(67, "Baritone Sax"),
            new SelectableIsntrument(68, "Oboe"),
            new SelectableIsntrument(69, "English Horn"),
            new SelectableIsntrument(70, "Bassoon"),
            new SelectableIsntrument(71, "Clarinet"),
            new SelectableIsntrument(72, "Piccolo"),
            new SelectableIsntrument(73, "Flute"),
            new SelectableIsntrument(74, "Recorder"),
            new SelectableIsntrument(75, "Pan Flute"),
            new SelectableIsntrument(76, "Bottle Blow"),
            new SelectableIsntrument(77, "Shakuhachi"),
            new SelectableIsntrument(78, "Whistle"),
            new SelectableIsntrument(79, "Ocarina"),
            new SelectableIsntrument(80, "Square Wave Lead"),
            new SelectableIsntrument(81, "Sawtooth Wave Lead"),
            new SelectableIsntrument(82, "Calliope Lead"),
            new SelectableIsntrument(83, "Chiff Lead"),
            new SelectableIsntrument(84, "Charang Lead"),
            new SelectableIsntrument(85, "Voice Lead"),
            new SelectableIsntrument(86, "Fifths Lead"),
            new SelectableIsntrument(87, "Bass Lead"),
            new SelectableIsntrument(88, "New Age Pad"),
            new SelectableIsntrument(89, "Warm Pad"),
            new SelectableIsntrument(90, "Polysynth Pad"),
            new SelectableIsntrument(91, "Choir Pad"),
            new SelectableIsntrument(92, "Bowed Pad"),
            new SelectableIsntrument(93, "Metallic Pad"),
            new SelectableIsntrument(94, "Halo Pad"),
            new SelectableIsntrument(95, "Sweep Pad"),
            new SelectableIsntrument(96, "Rain Effect"),
            new SelectableIsntrument(97, "Soundtrack Effect"),
            new SelectableIsntrument(98, "Crystal Effect"),
            new SelectableIsntrument(99, "Atmosphere Effect"),
            new SelectableIsntrument(100, "Brightness Effect"),
            new SelectableIsntrument(101, "Goblins Effect"),
            new SelectableIsntrument(102, "Echoes Effect"),
            new SelectableIsntrument(103, "Sci-Fi Effect"),
            new SelectableIsntrument(104, "Sitar"),
            new SelectableIsntrument(105, "Banjo"),
            new SelectableIsntrument(106, "Shamisen"),
            new SelectableIsntrument(107, "Koto"),
            new SelectableIsntrument(108, "Kalimba"),
            new SelectableIsntrument(109, "Bagpipe"),
            new SelectableIsntrument(110, "Fiddle"),
            new SelectableIsntrument(111, "Shanai"),
            new SelectableIsntrument(112, "Tinkle Bell"),
            new SelectableIsntrument(113, "Agogo"),
            new SelectableIsntrument(114, "Steel Drums"),
            new SelectableIsntrument(115, "Woodblock"),
            new SelectableIsntrument(116, "Taiko Drum"),
            new SelectableIsntrument(117, "Melodic Tom"),
            new SelectableIsntrument(118, "Synth Drum"),
            new SelectableIsntrument(119, "Reverse Cymbal"),
            new SelectableIsntrument(120, "Guitar Fret Noise"),
            new SelectableIsntrument(121, "Breath Noise"),
            new SelectableIsntrument(122, "Seashore"),
            new SelectableIsntrument(123, "Bird Tweet"),
            new SelectableIsntrument(124, "Telephone Ring"),
            new SelectableIsntrument(125, "Helicopter"),
            new SelectableIsntrument(126, "Applause"),
            new SelectableIsntrument(127, "Gun Shot")
    };

    public final int number;
    public final String name;

    public SelectableIsntrument(int number, String name) {
        this.number = number;
        this.name = name;
    }

    @Override
    public String toString() {
        return number + ". " + name;
    }
}
